# This file is a template, and might need editing before it works on your project.
#FROM php:7.4-apache-buster

#WORKDIR /app
# Edit with mysql-client, postgresql-client, sqlite3, etc. for your needs.
# Or delete entirely if not needed.
#RUN 
 #  -docker-php-ext-install mysqli
#RUN
 #  -docker-php-ext-enable mysqli
#RUN
 #  -docker-php-ext-install pdo pdo_mysql pdo_pgsql
FROM php:7.4-apache
COPY src/ /var/www/html/
